events {
    worker_connections  1024;
}
http {
    include mime.types;

    server {
        listen 8085;
        server_name localhost;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
